### ISSUE TITLE
General question:)

### ISSUE THREAD

**Issue by Ta7siin** [hackermondev/discord-active-developer-badge#23]
Hello !
do i need to let the bot always On after add it to the server ?
because my laptop is not always on and i need to wait 24H till i get the badge
so i need to let the bot on or i just can use the command (/ping) and let it off and wait normally ?

**Comment by Arch881010** [comment]
You only have to run it once! I would do it every so often (whenever you can, in your spare time). Like every 4+ hours and test it again. This way it'll try to register it again. Sometimes it takes >24 hours at a time, so patience is key!
