### ISSUE TITLE
Blocked Node?

### ISSUE THREAD

**Issue by Miapata** [hackermondev/discord-active-developer-badge#27]
I tried to run it on Replit, but once I enter the token, the following message comes up.

`Uh oh, looks like the node you're on is currently being blocked by Discord. Press the "Enter" button on your keyboard to be reassigned to a new node. (you'll need to rerun the program once you reconnect)`

I press Enter and rerun it, but it says the same thing. The program also stops after I press Enter.

**Comment by Miapata** [comment]
Solved! I just recloned it and it worked.

**Comment by Arch881010** [comment]
For future reference,
it’s supposed to stop the program. It kills your connection to it and makes you start it again.
If it didn’t kill it, you would be stuck with the same ip/blocked node, and won’t be able to start the bot.
