### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by im-the-one-who-knocks** [hackermondev/discord-active-developer-badge#34]
I did everything but at the end the bot just doesn't respond to the command

**Comment by Arch881010** [comment]
Sorry for the delayed response, what do you mean by it doesn’t respond? 
If it’s just “The application did not respond.”, then:
-Make sure your bot is running.
-Did you change anything in the app.js?

**Comment by im-the-one-who-knocks** [comment]
Don't worry i solved the problem, it was a problem with my computer it has nothing to do with your great work.
Wish you the best

**Comment by Arch881010** [comment]
Uhm.. replit issues should not be caused by your computer.
