### ISSUE TITLE
Coding problem

### ISSUE THREAD

**Issue by dailynobo** [hackermondev/discord-active-developer-badge#36]
![Image 08-03-2023 at 6 49 PM](https://user-images.githubusercontent.com/127323503/223746305-dc6981bd-8e31-4dde-9cf5-297ea91b05a1.jpeg)

**Comment by Arch881010** [comment]
Reset your token! You just exposed your token.
You also made the bot stopped running before you posted it! Thus, it was invalid.

**Comment by dailynobo** [comment]
> Reset your token! You just exposed your token. You also made the bot stopped running before you posted it! Thus, it was invalid.
