### ISSUE TITLE
Exit Status 1

### ISSUE THREAD

**Issue by exeScripter** [hackermondev/discord-active-developer-badge#37]
![Przechwytywanie](https://user-images.githubusercontent.com/68824919/226163949-3a5abd62-6174-4710-b4c3-a3420f5485a1.PNG)

**Comment by hackermondev** [comment]
I'm investigating this issue. I'll get back to you later.

**Comment by exeScripter** [comment]
Hi man, I just fixed the issue myself.
Have a great day.
