### ISSUE TITLE
weird issue or sumn

### ISSUE THREAD

**Issue by metNat** [hackermondev/discord-active-developer-badge#38]
When I run the bot, it works, but it goes offline after and when I try to do /ping again, it just gives me an error message. The only way I can fix it is by rerunning replit and putting in my application token back in, then it only works once again and the issue comes back.
I’m worried that this will prevent me from getting the badge.

**Comment by hackermondev** [comment]
Yeah, that's how it works. The bot can only respond to interactions when its running on Replit. This won't affect your ability to get the badge. You might need to rerun the bot and command every month to keep the badge but other than that, you're fine.
