### ISSUE TITLE
cant start

### ISSUE THREAD

**Issue by theOnecassu** [hackermondev/discord-active-developer-badge#40]
Application token? Hint: hit control+c anytime to enter REPL.
(node:313) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 
(To exit, press Ctrl+C again or Ctrl+D or type .exit)

it was working fine few days ago but now its dead nad reisntalling the whole thing doesnot help

**Comment by hackermondev** [comment]
Make sure you're pasting the token by Right Clicking on the terminal -> clicking paste.

**Comment by Steven-OS** [comment]
I'm encountering the same issue. I've definitely pasted the correct token in the terminal, tried to reinstall it, make a new token, and everything. It used to work perfectly fine a few weeks back, but not anymore.

**Comment by Arch881010** [comment]
Ive tested it out on a demo bot, it’s launched just fine.
Please make sure you are copying the token, and the full token. My token (that I have already reset) is `MTExMjQxMzI3MDAxMjM0MjMyMg.Gix4AM.ydFNCDM7M5b63_k-4c3IFi_S6QFltJfFTvBOeE`
Which means it should follow the same formatting. (Same length, the 3 periods. Characters/Numbers are randomized, my M could be 3 for example.)
Need any more help or have any info. Please comment. Thanks.

**Comment by Steven-OS** [comment]
I copied the Client Secret instead of token... all good now. Rookie mistake.
Your clarification fixed it, thank you!
