### ISSUE TITLE
Free Repl Is Not Working Anymore!

### ISSUE THREAD

**Issue by muhtalhakhan** [hackermondev/discord-active-developer-badge#47]
Repl is not allowing to use the resources freely. It only allows the users to use .5v CPU which is not enough for it.

**Comment by muhtalhakhan** [comment]
Nah, I don't mean that.
Actually, It's not allowing to consume the CPU more.

**Comment by Arch881010** [comment]
This shouldn’t effect much?

**Comment by muhtalhakhan** [comment]
Actually, it's stopping the script

**Comment by bburakguldogan** [comment]
❤️
