### ISSUE TITLE
No Respond

### ISSUE THREAD

**Issue by SX-9** [hackermondev/discord-active-developer-badge#9]
![SmartSelect_20221114-213736_Discord.jpg](https://user-images.githubusercontent.com/90962949/201687720-8af7b038-38b5-42af-9c71-613af746855f.jpg)

**Comment by hackermondev** [comment]
Is the program on Replit still running?

**Comment by Arch881010** [comment]
Also, as I've continued on working on the bot and using it myself, is there an error in the console? (It is stressed to NOT CLOSE THE TAB when using the bot.)

**Comment by Pandafishie** [comment]
Sometimes Replit programs stop running after a few hours. You'll have to restart them if you want your bot to be working again. You can do that by doing the following:
- Reload the Tab (Press "F5"     OR  the "Control" + "R" keys together )
- Click on "Run"
- Re-enter your token. Alternatively, you save your token in the script, if you want that.
- Done. Your app should be up and running again

If you want to keep your bot running 24/7, you'll have to host it yourself or find an npm (+ nodeJs) supporting host.
